name: run all tests

on: [push, pull_request]

jobs:
  test:
    strategy:
        fail-fast: false
        matrix:
            python-version: ["3.12"]

    runs-on: ubuntu-latest
    name: run tests
    steps:
      - uses: actions/checkout@v2
      - name: python
        uses: actions/setup-python@v1
        with:
            python-version: ${{ matrix.python-version }}
      - name: install requirements
        run: |
          sudo apt-get update && sudo apt-get install -y libcairo2-dev pkg-config python3-dev
          pip install wheel
          pip install mypy
          pip install .
      - name: mypy
        run: |
          mypy --config-file mypy.ini openglider
      - name: test
        run: |
          python testall.py
